# fly.toml app configuration file generated for wpt2 on 2024-04-25T02:35:07+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wpt2'
primary_region = 'syd'

[build]

[env]
  APP_ENV = 'production'
  DB_CONNECTION = 'mysql'
  DB_DATABASE = '<freedb_cub_111>'
  DB_HOST = '<sql.freedb.tech>'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'performance-16x'
