drop database asesoresprime_cub;
create database asesoresprime_cub;
use asesoresprime_cub;
-- MySQL Script generated by MySQL Workbench
-- Mon Mar 18 23:40:07 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema asesoresprime_cub
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema asesoresprime_cub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `asesoresprime_cub` ;
USE `asesoresprime_cub` ;

-- -----------------------------------------------------
-- Table `advisers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `advisers` (
  `id_adviser` INT(11) NOT NULL AUTO_INCREMENT,
  `adviser_username` VARCHAR(16) NOT NULL,
  `adviser_password` VARCHAR(60) NOT NULL,
  `adviser_role` VARCHAR(100) NOT NULL,
  `adviser_name` VARCHAR(100) NOT NULL,
  `adviser_lastname` VARCHAR(100) NOT NULL,
  `adviser_rut` VARCHAR(100) NOT NULL,
  `adviser_email` VARCHAR(100) NOT NULL,
  `adviser_phone` VARCHAR(30) NOT NULL,
  `registeredAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `adviser_birthday` DATE NOT NULL,
  PRIMARY KEY (`id_adviser`));


-- -----------------------------------------------------
-- Table `damages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `damages` (
  `id_damage` INT(11) NOT NULL AUTO_INCREMENT,
  `damage_name` VARCHAR(150) NOT NULL,
  `damage_description` TEXT NULL DEFAULT NULL,
  `damage_unit` VARCHAR(40) NOT NULL,
  `createdby` VARCHAR(40),
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_damage`));


-- -----------------------------------------------------
-- Table `repairs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `repairs` (
  `id_repair` INT(11) NOT NULL AUTO_INCREMENT,
  `repair_name` VARCHAR(150) NOT NULL,
  `repair_unit` VARCHAR(150) NOT NULL,
  `repair_price` DECIMAL(19,2) NOT NULL,
  `repair_description` TEXT NULL DEFAULT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_repair`));


-- -----------------------------------------------------
-- Table `sectors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sectors` (
  `id_sector` INT(11) NOT NULL AUTO_INCREMENT,
  `sector_name` VARCHAR(150) NOT NULL,
  `sector_description` TEXT NULL DEFAULT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_sector`));


-- -----------------------------------------------------
-- Table `clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clients` (
  `id_client` INT(11) NOT NULL AUTO_INCREMENT,
  `client_name` VARCHAR(100) NOT NULL,
  `client_lastname` VARCHAR(100) NOT NULL,
  `client_rut` VARCHAR(100) NOT NULL,
  `client_birthday` DATE NOT NULL,
  `client_address` VARCHAR(100) NOT NULL,
  `client_phone` VARCHAR(100) NOT NULL,
  `client_email` VARCHAR(100) NOT NULL,
  `registeredAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_client`));


-- -----------------------------------------------------
-- Table `incidents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incidents` (
  `id_incident` INT(11) NOT NULL AUTO_INCREMENT,
  `incident_code` VARCHAR(120) NOT NULL,
  `incident_date` DATE NOT NULL,
  `incident_description` TEXT NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_incident`));


-- -----------------------------------------------------
-- Table `status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `status` (
  `id_status` INT(11) NOT NULL,
  `status_name` VARCHAR(40) NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_status`));


-- -----------------------------------------------------
-- Table `cases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cases` (
  `id_case` INT(11) NOT NULL AUTO_INCREMENT,
  `id_status` INT(11) NOT NULL,
  `id_adviser` INT(11),
  `id_client` INT(11) NOT NULL,
  `id_incident` INT(11) NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `case_date` DATE NOT NULL,
  `case_img1` VARCHAR(200),
  `case_img2` VARCHAR(200),
  PRIMARY KEY (`id_case`),
  CONSTRAINT `fk_cases_status1`
    FOREIGN KEY (`id_status`)
    REFERENCES `status` (`id_status`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cases_advisers1`
    FOREIGN KEY (`id_adviser`)
    REFERENCES `advisers` (`id_adviser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cases_clients1`
    FOREIGN KEY (`id_client`)
    REFERENCES `clients` (`id_client`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cases_incidents1`
    FOREIGN KEY (`id_incident`)
    REFERENCES `incidents` (`id_incident`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `damages_repairs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `damages_repairs` (
  `id_damage_repair` INT(11) NOT NULL AUTO_INCREMENT,
  `id_damage` INT(11) NOT NULL,
  `id_repair` INT(11) NOT NULL,
  `createdby` VARCHAR(100),
  PRIMARY KEY (`id_damage_repair`),
  CONSTRAINT `fk_damages_has_repairs_damages1`
    FOREIGN KEY (`id_damage`)
    REFERENCES `damages` (`id_damage`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_damages_has_repairs_repairs1`
    FOREIGN KEY (`id_repair`)
    REFERENCES `repairs` (`id_repair`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `c_d_s`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `c_d_s` (
  `id_c_d_s` INT NOT NULL AUTO_INCREMENT,
  `id_damage` INT(11),
  `id_sector` INT(11) NOT NULL,
  `id_case` INT(11) NOT NULL,
  PRIMARY KEY (`id_c_d_s`),
  CONSTRAINT `fk_cases_has_damages_damages1`
    FOREIGN KEY (`id_damage`)
    REFERENCES `damages` (`id_damage`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_c_d_sectors1`
    FOREIGN KEY (`id_sector`)
    REFERENCES `sectors` (`id_sector`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_c_d_cases1`
    FOREIGN KEY (`id_case`)
    REFERENCES `cases` (`id_case`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `dimentions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dimentions` (
  `id_dimention` INT NOT NULL AUTO_INCREMENT,
  `sector_w_size` DECIMAL(19,2) NOT NULL,
  `sector_l_size` DECIMAL(19,2) NOT NULL,
  `sector_h_size` DECIMAL(19,2) NOT NULL,

  `img1` VARCHAR(200) NOT NULL,
  `img2` VARCHAR(200) NOT NULL,

  `id_sector` INT(11) NOT NULL,
  `id_case` INT NOT NULL,
  PRIMARY KEY (`id_dimention`),
  CONSTRAINT `fk_dimentions_sectors1`
    FOREIGN KEY (`id_sector`)
    REFERENCES `sectors` (`id_sector`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dimentions_cases1`
    FOREIGN KEY (`id_case`)
    REFERENCES `cases` (`id_case`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);



-- -----------------------------------------------------
-- Table `d_c_d_s`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `d_c_d_s` (
  `id_d_c_d_s` INT NOT NULL AUTO_INCREMENT,
  `id_c_d_s` INT NOT NULL,
  `size` DECIMAL(10) NOT NULL,
  `customized` INT(1),
  PRIMARY KEY (`id_d_c_d_s`),
  CONSTRAINT `fk_d_c_d_s_c_d_s1`
    FOREIGN KEY (`id_c_d_s`)
    REFERENCES `c_d_s` (`id_c_d_s`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);

-- -----------------------------------------------------
-- Table `damage_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `damage_images` (
  `id_damage_images` INT NOT NULL AUTO_INCREMENT,
  `image1` VARCHAR(200) NOT NULL,
  `image2` VARCHAR(200) NULL,
  `image3` VARCHAR(200) NULL,
  `id_d_c_d_s` INT NOT NULL,
  PRIMARY KEY (`id_damage_images`),
  CONSTRAINT `fk_damage_images_d_c_d_s1`
    FOREIGN KEY (`id_d_c_d_s`)
    REFERENCES `d_c_d_s` (`id_d_c_d_s`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);

-- -----------------------------------------------------
-- Table `budgets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `budgets` (
  `cases_id_case` INT(11) NOT NULL AUTO_INCREMENT,
  `budget` VARCHAR(300) NULL,
  `id_case` INT(11) NOT NULL,
  `createAt` TIMESTAMP NOT NULL,
  CONSTRAINT `fk_table1_cases1`
    FOREIGN KEY (`cases_id_case`)
    REFERENCES `cases` (`id_case`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);
